### ISSUE TITLE
TOML Parser: Misleading "Line No" on Error

### ISSUE THREAD

**Issue by sanket143** [chapel-lang/chapel#12843]
for following toml file
```toml
[owner]
name = "Foo Bar" # Full Name
dob = 2000-30-04-23
```

```chpl
use TOML;

const tomlFile = open("example.toml", iomode.r);
const toml = parseToml(tomlFile);
const name = toml["owner"]["name"];

writeln(name.toString());
```

gave this error ``Line 4: Illegal Value -> 2000-30-04-234-234`` instead of ``Line 3: Illegal Value -> 2000-30-04-234-234``

It worked as expected for following toml file
```toml
[owner]
name = "Foo Bar"
dob = 2000-30-04-23
```

Having problem with inline comments
