### ISSUE TITLE
Handle escaped quotes in TOML strings

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#13332]
A user reported an error with including escaped quotes within a TOML field, e.g.

```toml
[brick]
compopts = "--arg=\"foobar\""
```

However, an available work-around is to use a different quote style:

```toml
[brick]
compopts = '--arg=\"foobar\"'
```
