### ISSUE TITLE
Is chpl --static supported with mason's pkg-config integration?

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#13790]
### Summary of Problem
General question. Possible bug report or feature request(?).

Disclaimer: I haven't actually tried the mason pkg-config support yet, so this might work fine.

When creating a Mason project that has an external pkg-config dependency, does `chpl --static` work with it?

Specifically, pkg-config can take `--static` to denote static linkage, in which the flags will change. This is important because `chpl --static` will try to link all libraries statically, which will certainly fail if a pkg-config library has dependencies that are not outputted by using `pkg-config --static`.

However, you can't just use `pkg-config --static` naively because pkg-config throws in a bunch of extra C/C++-compiler flags; the Chapel compiler does not take these extra flags.

For example, with a custom-installed ZeroMQ with a dependency on libsodium:
```terminal
$> pkg-config --libs libzmq
-L/libzmq/lib -lzmq
# chpl --static will fail with this output because -lsodium is missing.
$> pkg-config --static --libs libzmq
-L/libsodium/lib -L/libzmq/lib -lzmq -lstdc++ -lpthread -lrt -lsodium -pthread
```
(I think -pthread is the only flag that is *technically* not supported. Is -lstdc++ safe?)

The Chapel compiler could support those extra flags and ignore them, but I think that's kind of hacky, but I'm not sure what a proper solution would look like.

The workaround I would use today is to specify each dependency manually (e.g., in a Makefile):
```make
LIBS := $(shell pkg-config --libs libzmq) $(shell pkg-config --libs libsodium)
```
but this is brittle if you use the Makefile on a system that didn't build libzmq with libsodium. Or worse: some library is used that has lots of dependencies.

**Comment by BryantLam** [comment]
Note that I don't have a use case to link ZMQ statically. It's just a convenient example that I was working on.

**Comment by Spartee** [comment]
@BryantLam So you are asking two questions here I believe. The first has to do with using ``pkg-config`` directly with the ``chpl`` compiler when compiling with ``--static``. For that question I am going to link @lydia-duncan.

As far as mason is concerned, we do not support any of the direct pkg-config modifications(as in, including ``--static``) as of today. However, we do allow for the user to place compilation options in the ``Mason.toml`` so that these kinds of cases can be handled. The process would be fairly manual however we support ``mason system pc <package>`` so that the flags can be viewed quickly. For example

```toml
# Mason.toml
[brick]
name = "cholskey"
chplVersion = "1.18.0"
compopts = "--ccflags -Wno-enum-conversion --ccflags -Wno-strict-prototypes"

[dependencies]

[system]
lapack = "*"
```

```toml
# Mason.lock
[root]
name = "cholesky"
compopts = "--ccflags -Wno-enum-conversion --ccflags -Wno-strict-prototypes"
version = "0.1.0"
chplVersion = "1.18.0..1.18.0"

[system]

[system.lapack]
name = "lapack"
version = "3.8.0"
libs = "-L/usr/local/Cellar/lapack/3.8.0_1/lib -llapack"
include = "/usr/local/Cellar/lapack/3.8.0_1/include"
```
As you can see, right now mason will only go and get the output of the ``pkg-config --libs <package>`` and ``pkg-config --variable=includedir <package>`` and place them in the path of mason build.

So in your case, if you wanted to compile the package statically, you would first figure out which extra flags you need to include from ``pkg-config --libs --static``, place them in ``compopts``, list the packages you need under the ``[system]`` table, and build using ``mason build - --static`` as the dash allows you to pass arguments to the chapel compiler. 

Hope this helps! maybe @ben-albrecht would also have good insight here.
