### ISSUE TITLE
Toml parser: cannot parse table headers with quotes and periods in it

### ISSUE THREAD

**Issue by ankingcodes** [chapel-lang/chapel#16090]
While integrating `mason search` with the recent changes proposed to mason-registry, i.e, the `cache.toml` file for storing package ranks, it was found that the Toml parser failed to parse Toml headers which had quotes or periods in them. For example, 
```toml 
[LocalAtomics."0.1.0"]
score = "5"

[GPUIterator."0.0.1"]
score = "3"
```
The error on parsing is as follows : 
```
Line : 3 Unexpected token -> GPUIterator. 
```
This is due to the fact that `"0.0.1" is treated as a separate token.
Related to https://github.com/chapel-lang/mason-registry/issues/49 & #7104
