### ISSUE TITLE
[feature request] support github actions for mason packages

### ISSUE THREAD

**Issue by lucaferranti** [chapel-lang/chapel#20090]
(continuing from [this discussion](https://chapel.discourse.group/t/github-actions-ci-for-mason-packages/13560?u=lucaferranti) on discourse)

I think it would be great to have some support for github actions integration with mason packages. Basically, I would like the CI to automatically run `mason test` whenever I push to a branch (or to a PR or similar). Some integration with codecov could also be nice, but not that critical.

To my understanding (but to be clear, I am no expert on the topic), supporting this would require to create an action that setups chapel and runs the tests, github has [some docs](https://docs.github.com/en/actions/creating-actions) about this, don't know how tricky to actually implement though :smiley: Brad also pointed out that there are already some actions for chapel, so it might be that the hard part is already there and just needs to be documented / polished for the end-user.

**Comment by bradcray** [comment]
Tagging @ronawho here because of his expertise with GitHub actions.
Tagging @bmcdonald3 and @arezaii due to the mason connection.

**Comment by ronawho** [comment]
https://gitter.im/chapel-lang/chapel?at=625effbe8db2b95f0ac3c39b has some starter instructions I posted a while ago for setting up CI testing using chapel's docker image. Copying that here:

"""
Here's my (untested) starter template for mac/linux testing that runs on every push/PR:

```yml
name: CI

on: [push, pull_request]

jobs:
  linux_tests:
    runs-on: ubuntu-latest
    container:
      image: chapel/chapel # or chapel/chapel-gasnet-smp if you want multi-locale
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        # install any application deps
    - name: Build Application
      run: |
        make
    - name: Run tests
      run: |
        make check

  mac_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew install chapel
        # install any application deps
    - name: Build Application
      run: |
        make
    - name: Run tests
      run: |
        make check
```

Unfortunately, it's not trivial to have a simple matrix job that tests on both mac and linux since the container set up or dependency install isn't the same, but it's usually not too bad to duplicate the actual test steps.
"""


I think it's pretty straightforward to set this up and you'd just want to swap out the `make` / `make check` steps for whatever mason commands you want to run.

We could also create an action that would remove some of the boilerplate. Basically something that would take care of installing chapel and then run some standard mason build/test commands, but for now I'd recommend this more manual approach.
