### ISSUE TITLE
Mason: Chapel Versioning

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#7279]
## Chapel Versioning in Mason

Add support for a `chplVersion` field in `Mason.toml`:

``` toml

[brick]
name = "MyPackage"
version = "0.1.0"
chplVersion = "1.16.0"

```

### field name options

- **`chplVersion`**
- ~`chpl`~
- ~`chapelVersion`~

## Range Syntax

Ranges are specified with Chapel syntax:

``` toml

[brick]
name = "MyPackage"
version = "0.1.0"
chplVersion = "1.13.0..1.16.0"

``` 

minor-minor releases can be implied:

``` toml

[brick]
name = "MyPackage"
version = "0.1.0"
chplVersion = "1.13..1.16"

``` 

minor releases *cannot* be implied:

``` toml

[brick]
name = "MyPackage"
version = "0.1.0"
chplVersion = "1" # invalid

``` 
"... or later" ranges are expressed by a single version and include later major versions:

``` toml

[brick]
name = "MyPackage"
version = "0.1.0"
chplVersion = "1.16.0" # 1.16, 1.17, 2.0, 10.10.10

``` 

## Default Value

When creating a package with `mason new`, the default `chplVersion` is the version of the available `chpl` compiler that `mason` is currently using. This means that by default the package is assumed to work with later versions of the compiler and standard modules.

## Dependency Resolution

When resolving  package versions, only packages matching the current Chapel compiler version should be considered. There is no dependency resolution strategy for Chapel versions themselves.
