### ISSUE TITLE
Mason Test

### ISSUE THREAD

**Issue by Spartee** [chapel-lang/chapel#9840]
Enable the `mason test` command which will compile and run the `.chpl` files within the test sub-directory of a mason project that are listed in the `Mason.toml` file.

An example of the manifest file addition is listed below:

```toml

[brick]
name = "masonProject"
version = "0.0.1"
chplVersion = "1.17.0"
tests = ["test-1.chpl", "test-2.chpl"]

[dependencies]
```

This issue is an effort to provide mason users with temporary way of testing their projects while we develop a fully fledged testing system to work with mason.
